### ISSUE TITLE
[deconz] Enable logs

### ISSUE THREAD

**Issue by junalmeida** [smarthomej/addons#130]
How do I enable logs for using deconz? 

I have: 
![image](https://user-images.githubusercontent.com/991675/121779480-792a1780-cb61-11eb-963e-fef0947a681c.png)

Yet I see no logs for http calls in frontail. But binding is working as I see some state changes coming from deconz.

**Comment by J-N-K** [comment]
`log:set TRACE org.smarthomej.binding.deconz` is correct for logging all requests. Do you see the log messages if you use `log:tail` on the console? If that is the case, maybe fronttail uses a filter?

**Comment by junalmeida** [comment]
I also tried TRACE and I couldn't see any on either fronttail or `log:tail`.

**Comment by J-N-K** [comment]
That's strange, because that is exactly what I use. Please show `list -s | grep -i deconz` from the karaf console.

**Comment by junalmeida** [comment]
![image](https://user-images.githubusercontent.com/991675/121903008-79571e00-cced-11eb-9b6f-4b90e523ea11.png)

**Comment by junalmeida** [comment]
Any idea ?

**Comment by J-N-K** [comment]
Sorry, I didn't look closely enough. Since everything is within the `internal` package and you configured that to gave the log level `WARN` only `WARN` and `ERROR` will be logged. You can un-set that with `log:set DEFAULT org.smarthomej.binding.deconz.internal`. 

Then the `DEBUG` setting will be used. Otherwise it will be ignored, because the `WARN` setting is more specific.
