### ISSUE TITLE
Switchbot Pan/Tilt Camera no Camera Stream

### ISSUE THREAD

**Issue by BangerTech** [smarthomej/addons#383]
Hi and first of all thanks for the Binding! Great job!
I got a Switchbot Pan/Tilt Camera the other day and it works like other Tuya Cams too. I connected it in the SmartLife App and with your Binding i can add it to openHAB3. The only Problem is there is no Camera Stream Channel. 
On HomeAssistant there is no Problem with the Tuya integration i get a camera Stream right away. 
I´ve tried to setup a manual channel but this didn´t work as well. Do you have any idea what i can do?

Thanks again and kindest regards.

**Comment by J-N-K** [comment]
I don't have such a camera. What channels are added?

**Comment by BangerTech** [comment]
thanks for the reply. 
ok i´m just wondering why there is no stream channel or something. 
here is the full list
<img width="484" alt="Screenshot 2022-07-05 185339" src="https://user-images.githubusercontent.com/73241309/177378361-c0906634-0f41-497b-8487-c8eabe772088.png">

**Comment by J-N-K** [comment]
I guess that's because the schema does not provide such a channel. Is it this model 

https://www.amazon.de/SwitchBot-Überwachungskamera-Sichtfeldabdeckung-Bewegungserkennung-Bewegungsverfolgung/dp/B09WCQP14H

?

**Comment by BangerTech** [comment]
yes exactly thats the camera. 
integrated it in HomeAssistant and had almost the same channels (entities) but there was one more streaming channel :-(
maybe i need to create a channel manually?

**Comment by J-N-K** [comment]
If I'm not mistaken HomeAssistant uses the Tuya Cloud for connecting the devices. It's possible that some functionality is not available for local control. Which category is the device? If you log-in to iot.tuya.com and go to

- the device overview in your cloud project and click on "Debug device" or
- the API Explorer / Device Management / Get Device Details or
- the API Explorer / Device Control / Get Device specifications

do you see something that looks like a value that could provide the stream URL? Unfortunately I don't have a use-case for another indoor cam, otherwise I would have ordered one to check out myself.

**Comment by BangerTech** [comment]
so in device debugging i don´t see any stream url or something only one thing called movement_detect_pic RAW
nothing else which let me think there is a stream url. 
Product Category is: sp
for the api explorer stuff i couldn´t find anything too but i´m not a pro on the tuya iot platform ;-)
i thought homeassistant uses kinda the same method with the iot platform, because i use the same cloud project as with openhab.

**Comment by J-N-K** [comment]
Yes and no. They use the same project, but with cloud access, while we use local access. I also found out why they can show the video stream: You have to add the "IoT Video Live Stream" API to your project. But this is a paid API. I'll check if I can add something so you can use it.
