### ISSUE TITLE
Add access to thing configuration

### ISSUE THREAD

**Issue by clinique** [smarthomej/addons#425]
Currently ``org.openhab.core.config`` is not reachable from within rules. Could it be added to core dependencies made available ?

**Comment by J-N-K** [comment]
You should be able to do that yourself. Since the configuration of add-ons besides bindings is currently not supported by UI (and this will probably not change before OH4), I implemented a workaround. Go to the "Things" configuration page, then to "Add thing". You'll also see "Java Automation" and next to it a gear wheel. Click on that and add the bundle you need to the list. Done.

**Comment by clinique** [comment]
Correct, I forgot this. Thanks.

**Comment by clinique** [comment]
I've tried this but unfortunately it does not seems to add the bundle to core-dependency.jar : 
![image](https://user-images.githubusercontent.com/3328789/205508781-1db219b2-44dc-47a9-a3d1-2e2bcbbb8a15.png)
