### ISSUE TITLE
[Viessmann] no gas-consumption-values with a VitoDens 222-F

### ISSUE THREAD

**Issue by LukaNoah** [smarthomej/addons#462]
Hi,
all gas-consumption values are NULL, I see the values in the ViCare-App and web. Can this be fixed?
Can also all basic-api-values add to the binding for heating devices?

Thank you

**Comment by rogrun** [comment]
Hi, 

Since when are all gas-consumptions NULL or was that never working? Or are the values ​​UNDEF?

All basic-api-values should be added automatically. Wich values do you miss?

For more debugging please email me the log in TRACE mode by typing in the OpenHAB console: `log:set TRACE org.smarthomej.binding.viessmann`

I'll take a look at this as soon as possible. 

Here is my mail address: ronny.grun@t-online.de

**Comment by LukaNoah** [comment]
Hello,
the values for the various gas consumptions have never worked. They are UNDEF (look at the screenshot).
I miss the following values:
- heating.boiler.temperature Shows the set target temperature value of the boiler
- heating.dhw.charging Shows whether the hot water charging for the DHW storage is currently active

Hm, the exhaust gas temperature is not included in the API, but it is in the app. Well then I have to live with it.
I'll send you the trace log.

![image](https://user-images.githubusercontent.com/16850444/222665569-cbc04122-cdca-44b6-ab6f-a6852a60f730.png)

**Comment by rogrun** [comment]
@J-N-K Can you please create a new release? This issue was resolved by PR #431

**Comment by LukaNoah** [comment]
... I have to read ;)

Should I create a new issue for the missing values?

**Comment by rogrun** [comment]
3.2.16 is currently not released, but you can download pre-release here:
[https://download.ronnygrun.de/shj-viessmann3.2.16.zip](https://download.ronnygrun.de/shj-viessmann3.2.16.zip)

Before copying the two files you have to uninstall the binding and the `org.smarthomej.commons`

After that, fist put the commons in the addons folder and then the viessmann binding.
